- type: worldGen
  id: default
  data:
    noiseWorld:
      - amplitude: 1
        noise:
          noiseType: Perlin
          frequency: 0.02
    tileElevation: 
      0: water
      0.1: sand
      0.2: grass
    defaultTile: water
    additions: 
      - !type:EntWorldGenAddition
        entity: Grass
        spawnСhance: 0.25
        randomAngleMax: 90
        tileWhitelist:
          - grass
      - !type:EntWorldGenAddition
        entity: Tree
        spawnСhance: 0.15
        randomAngleMax: 90
        tileWhitelist:
          - grass
