- type: worldGen
  id: default
  data:
    noiseWorld:
      - amplitude: 1
        noise:
          noiseType: Perlin
          frequency: 0.02
    tileElevation: 
      0: grass
      0.1: sand
      0.3: grass
    defaultTile: water
    additions: 
      - !type:EntWorldGenAddition
        entity: Wall
        conditions:
          - !type:TileCondition
            tileWhitelist:
              - grass  
          - !type:AdjacentTileRequiredCondition
            tiles:
              - sand
        
      - !type:EntWorldGenAddition
        entity: Grass
        randomAngleMax: 90
        conditions:
          - !type:TileCondition
            tileWhitelist:
              - grass
          - !type:SpawnProbabilityCondition
            spawnProbability: 0.25
      - !type:EntWorldGenAddition
        entity: Tree
        randomAngleMax: 90
        conditions:
          - !type:TileCondition
            tileWhitelist:
              - grass
          - !type:SpawnProbabilityCondition
            spawnProbability: 0.15
