using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Indicators.Controls;

[GenerateTypedNameReferences]
public sealed partial class IndicatorProgressBar : Control
{
    public IndicatorProgressBar()
    {
        RobustXamlLoader.Load(this);
    }
}